Repository CHaserDevs/CHaserLua, pull requests merged in 2024-10, with the labels that each got.

#4 Add description of getReady() to README.md
  README.md
Labels: Category::Documentation

#5 Add LICENSE
  LICENSE
Labels: Category::Documentation

#8 fix syntax
  README.md
Labels: Category::Documentation, Level::Low

#7 :memo: Fix: fix invaild links
  README.md
Labels: Category::Documentation, Level::Medium

#9 Add/additional funcs
  README.md
  connect.lua
Labels: Category::Documentation, Category::Enhancements, Level::High

#11 Create LICENSE
  LICENSE
Labels: Category::Documentation, Level::High
